language: python
python: '2.7'
before_script: mkdir -p shippable/codecoverage
install: pip install -r requirements.txt -r requirements_test.txt
script: 
  - py.test test_server.py --cov views
  - coverage run --branch test_server.py
  - coverage xml -o shippable/codecoverage/coverage.xml test_server.py
  
